### ISSUE TITLE
How can I iterate through objects? 

### ISSUE THREAD

**Issue by ericmaro** [FalconWiz/falcon-invoice#1]

**Comment by FalconWiz** [comment]
Hello! Could you please give me more information about what you're trying to do? Thanks!

**Comment by FalconWiz** [comment]
Closing issue for now. I suggest you check out for...in and for...of loops on the mozilla site (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in) for more information on loops in Javascript.
