### ISSUE TITLE
Last version not pushed on npm repo

### ISSUE THREAD

**Issue by tinquen12** [FalconWiz/falcon-invoice#3]
Hello,

It seems that npm repository is not up to date. In fact, the function is not returning the promise like the code from github does.

Is it possible to push it ?

Thank you very much 😃

**Comment by FalconWiz** [comment]
Hello! You're right, I meant to push the updated version months ago about but ended up forgetting haha. Sorry about that, it has been updated now.

https://www.npmjs.com/package/falcon-invoice

Thanks! 🎉

**Comment by tinquen12** [comment]
It happens ahah 😄 
Thanks !!
